# Ref: default config, with minor tweaks
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Include:
    - '{lib,spec}/**/*.rb'
    - 'Gemfile'
    - 'Gemfile.rack-1.x'
    - 'rack-test.gemspec'
    - 'Rakefile'
    - 'Thorfile'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

# Rationale: defalt approach forces us to indent multiline `foo = if bar` statements in an unreasonable way.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

inherit_from: .rubocop_todo.yml
